---
# compute-video-demo-ansible
- name: Destroy all demo resources
  hosts: local
  gather_facts: False
  vars_files:
    - gce_vars/auth
    - gce_vars/machines
    - gce_vars/zonea
    - gce_vars/zoneb
    - gce_vars/lb
  tasks:
    - name: Destroy the instances in the first zone
      gce:
        instance_names: "{{ names_zonea }}"
        zone: "{{ zonea }}"
        project_id: "{{ pid }}"
        pem_file: "{{ pem }}"
        service_account_email: "{{ email }}"
        state: absent
    - name: Destroy the instances in the second zone
      gce:
        instance_names: "{{ names_zoneb }}"
        zone: "{{ zoneb }}"
        project_id: "{{ pid }}"
        pem_file: "{{ pem }}"
        service_account_email: "{{ email }}"
        state: absent
    - name: Destroy the firewall rule
      gce_net:
        fwname: all-http
        project_id: "{{ pid }}"
        pem_file: "{{ pem }}"
        service_account_email: "{{ email }}"
        state: absent
    - name: Destroy the load-balancer
      gce_lb:
        name: varnish
        region: "{{ region }}"
        project_id: "{{ pid }}"
        pem_file: "{{ pem }}"
        service_account_email: "{{ email }}"
        state: absent
    - name: Make sure the persistent disks are destroyed
      gce_pd: name={{ item.name }} zone={{ item.zone }} state=absent
              project_id={{ pid }} pem_file={{ pem }} service_account_email={{ email }}
      with_items:
        - { name: "walla-varnish1", zone: "us-central1-a" }
        - { name: "walla-varnish3", zone: "us-central1-a" }
        - { name: "walla-varnish2", zone: "us-central1-b" }
        - { name: "walla-varnish4", zone: "us-central1-b" }
        - { name: "walla-varnish5", zone: "us-central1-a" }
        - { name: "walla-varnish7", zone: "us-central1-a" }
        - { name: "walla-varnish6", zone: "us-central1-b" }
        - { name: "walla-varnish8", zone: "us-central1-b" }

